name: Branch and Commit Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  branch_commit_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify branch name
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "Error: Pushes are only allowed to the main branch."
            exit 1
          fi

          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.base_ref }}" != "main" ]]; then
            echo "Error: Pull requests must target the main branch."
            exit 1
          fi