name: Branch and Commit Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify branch name
        run: |
          if [ "${{ github.ref }}" != "refs/heads/main" ]; then
            echo "Error: Pushes are only allowed to the main branch."
            exit 1
          fi

      - name: Verify commit message
        run: |
          if ! git log -1 --pretty=%B | grep -qE "^(feat|fix|docs|style|refactor|test|chore):"; then
            echo "Error: Commit message must follow the conventional format (e.g., feat: add new feature)."
            exit 1
          fi